repos:
  - repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.10
    hooks:
      - id: ruff-check

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        args: ["--toml=backend/pyproject.toml"]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run --directory backend mypy
        language: system
        types: [python]
        pass_filenames: false
        require_serial: true
