"use client";

import { useId } from "react";

import { confidenceLabel } from "@/lib/telemetry";
import { NLInsightEvidence, NLInsightResponse } from "@/lib/types";
import { formatRelativeTime } from "@/lib/usage";

interface NLInsightCardProps {
  nlEnabled: boolean;
  response: NLInsightResponse | null;
  loading: boolean;
  generating: boolean;
  onGenerate: () => void;
  onEvidenceClick: (evidence: NLInsightEvidence) => void;
}

export function NLInsightCard({
  nlEnabled,
  response,
  loading,
  generating,
  onGenerate,
  onEvidenceClick,
}: NLInsightCardProps) {
  const titleId = useId();

  if (!nlEnabled) {
    return (
      <section className="panel tm-chart-card tm-nl-card" aria-labelledby={titleId}>
        <header className="tm-chart-head">
          <h3 id={titleId}>AI insight</h3>
          <span className="tm-nl-badge">Opt-in</span>
        </header>
        <p className="muted tm-chart-empty tm-nl-optin">
          Off by default. Turning this on sends the on-screen aggregates and a
          bounded set of redacted drilldown rows (session id, normalized tool
          name, timestamp, outcome, model) to your configured coding agent for
          a plain-language digest — never raw prompts, tool arguments, or
          paths. Set <code>telemetry_nl.enabled</code> in{" "}
          <code>waypoint.yaml</code> (or <code>WAYPOINT_TELEMETRY_NL_ENABLED</code>)
          to turn it on.
        </p>
      </section>
    );
  }

  if (loading && !response) {
    return <div className="panel tm-chart-card is-loading" aria-busy="true" />;
  }

  const insight = response?.insight ?? null;

  if (!insight) {
    return (
      <section className="panel tm-chart-card tm-nl-card" aria-labelledby={titleId}>
        <header className="tm-chart-head">
          <h3 id={titleId}>AI insight</h3>
        </header>
        <p className="muted tm-chart-empty">No digest yet for this range.</p>
        <button
          type="button"
          className="tm-insight-evidence"
          onClick={onGenerate}
          disabled={generating}
        >
          {generating ? "Generating…" : "Generate now"}
        </button>
      </section>
    );
  }

  return (
    <section className="panel tm-chart-card tm-nl-card" aria-labelledby={titleId}>
      <header className="tm-chart-head">
        <h3 id={titleId}>
          {response?.available ? "Insights available" : "AI insight"}
        </h3>
        <span className="tm-nl-badge" title="Generated by a coding agent, not measured directly">
          {confidenceLabel(insight.confidence)} confidence
        </span>
      </header>

      <p className="tm-nl-label">AI-generated — links to evidence, not a measured outcome</p>
      <p className="tm-insight-statement tm-nl-prose">{insight.prose}</p>

      {insight.evidence.length > 0 ? (
        <ul className="tm-nl-evidence-list">
          {insight.evidence.map((evidence, i) => (
            <li key={`${evidence.metric}:${i}`} className="tm-nl-evidence-row">
              <span className="tm-nl-evidence-text">
                {evidence.statement} <strong>{evidence.value}</strong>
              </span>
              <button
                type="button"
                className="tm-insight-evidence"
                onClick={() => onEvidenceClick(evidence)}
              >
                View →
              </button>
            </li>
          ))}
        </ul>
      ) : null}

      <p className="tm-nl-disclaimer muted">{insight.disclaimer}</p>

      <footer className="tm-nl-footer">
        <span className="muted">
          {formatRelativeTime(insight.generated_at)} · {insight.source_backend}
          {insight.source_model ? ` · ${insight.source_model}` : ""}
          {response?.stale ? " · stale" : ""}
        </span>
        <button
          type="button"
          className="tm-insight-evidence"
          onClick={onGenerate}
          disabled={generating}
        >
          {generating ? "Regenerating…" : "Regenerate"}
        </button>
      </footer>
    </section>
  );
}
